"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { mkdir, writeFile, unlink } from "fs/promises";
import path from "path";
import { db } from "@/db";
import { media } from "@/db/schema";
import { eq } from "drizzle-orm";
import { requireAdminSession } from "@/lib/auth";
import { toPositiveInt } from "@/lib/validation";
import { isCloudinaryConfigured, getCloudinaryClient } from "@/lib/cloudinary";
import type { UploadApiResponse } from "cloudinary";

const UPLOAD_DIR = path.join(process.cwd(), "public", "uploads");

/**
 * Upload hardening:
 * - Only an explicit allow-list of raster image / video-container types is
 *   accepted. SVG is deliberately rejected: it is script-capable and would be
 *   stored XSS when served from our own origin.
 * - The declared MIME type must agree with the file's magic bytes, so an HTML
 *   page or script cannot be smuggled in behind an `image/png` label.
 * - The stored filename is generated by us (never derived from user input), so
 *   path traversal, extension spoofing and overwrite attacks are impossible.
 * - Size is capped before anything is written to disk.
 */
const MAX_UPLOAD_BYTES = 8 * 1024 * 1024; // 8 MB

type DetectedType = {
  /** Canonical MIME type stored in the database. */
  mime: string;
  /** Accepted values for the browser-supplied content type. */
  declaredMimes: string[];
  extension: string;
  detect: (bytes: Uint8Array) => boolean;
};

function asciiAt(bytes: Uint8Array, offset: number, text: string): boolean {
  for (let index = 0; index < text.length; index += 1) {
    if (bytes[offset + index] !== text.charCodeAt(index)) return false;
  }
  return true;
}

function byteAt(bytes: Uint8Array, offset: number, signature: number[]): boolean {
  for (let index = 0; index < signature.length; index += 1) {
    if (bytes[offset + index] !== signature[index]) return false;
  }
  return true;
}

/** ISO Base Media File Format (MP4/AVIF) container with one of the given brands. */
function isIsoBmff(bytes: Uint8Array, brands: string[]): boolean {
  return asciiAt(bytes, 4, "ftyp") && brands.some((brand) => asciiAt(bytes, 8, brand));
}

const ALLOWED_TYPES: DetectedType[] = [
  {
    mime: "image/jpeg",
    declaredMimes: ["image/jpeg", "image/jpg", "image/pjpeg"],
    extension: ".jpg",
    detect: (bytes) => byteAt(bytes, 0, [0xff, 0xd8, 0xff]),
  },
  {
    mime: "image/png",
    declaredMimes: ["image/png"],
    extension: ".png",
    detect: (bytes) => byteAt(bytes, 0, [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
  },
  {
    mime: "image/gif",
    declaredMimes: ["image/gif"],
    extension: ".gif",
    detect: (bytes) => asciiAt(bytes, 0, "GIF8"),
  },
  {
    mime: "image/webp",
    declaredMimes: ["image/webp"],
    extension: ".webp",
    detect: (bytes) => asciiAt(bytes, 0, "RIFF") && asciiAt(bytes, 8, "WEBP"),
  },
  {
    mime: "image/avif",
    declaredMimes: ["image/avif"],
    extension: ".avif",
    detect: (bytes) => isIsoBmff(bytes, ["avif", "avis"]),
  },
  {
    mime: "video/mp4",
    declaredMimes: ["video/mp4", "video/x-m4v", "application/mp4"],
    extension: ".mp4",
    detect: (bytes) => isIsoBmff(bytes, ["isom", "iso2", "iso4", "iso5", "iso6", "mp41", "mp42", "avc1", "dash"]),
  },
  {
    mime: "video/webm",
    declaredMimes: ["video/webm"],
    extension: ".webm",
    detect: (bytes) => byteAt(bytes, 0, [0x1a, 0x45, 0xdf, 0xa3]),
  },
];

function detectType(bytes: Uint8Array): DetectedType | null {
  return ALLOWED_TYPES.find((type) => type.detect(bytes)) ?? null;
}

/** Redirect back to the library with a fixed error code (never user-supplied text). */
function rejectUpload(code: "too_large" | "unsupported_type" | "type_mismatch" | "upload_failed"): never {
  redirect(`/dashboard/media?error=${code}`);
}

/** Upload buffer directly to Cloudinary using upload_stream */
async function uploadToCloudinary(
  buffer: Buffer,
  folder: string,
  resourceType: "image" | "video" | "auto" = "auto"
): Promise<UploadApiResponse> {
  const cloudinary = getCloudinaryClient();
  return new Promise((resolve, reject) => {
    const stream = cloudinary.uploader.upload_stream(
      {
        folder,
        resource_type: resourceType,
      },
      (error, result) => {
        if (error || !result) {
          reject(error || new Error("Cloudinary upload failed"));
        } else {
          resolve(result);
        }
      }
    );
    stream.end(buffer);
  });
}

/** Extract Cloudinary public_id from secure_url to delete if needed */
function extractCloudinaryPublicId(url: string): { publicId: string; resourceType: "image" | "video" } | null {
  try {
    const parsed = new URL(url);
    if (!parsed.hostname.includes("cloudinary.com")) return null;

    // URL pattern: /<cloud_name>/<resource_type>/upload/(v<version>/)?<public_id>.<ext>
    const parts = parsed.pathname.split("/").filter(Boolean);
    const uploadIndex = parts.indexOf("upload");
    if (uploadIndex === -1 || uploadIndex >= parts.length - 1) return null;

    const resourceType = parts[uploadIndex - 1] === "video" ? "video" : "image";
    let remainder = parts.slice(uploadIndex + 1);

    // Skip version if present e.g. v1234567890
    if (remainder[0] && /^v\d+$/.test(remainder[0])) {
      remainder = remainder.slice(1);
    }

    const fullPath = remainder.join("/");
    // Strip file extension
    const lastDotIndex = fullPath.lastIndexOf(".");
    const publicId = lastDotIndex !== -1 ? fullPath.slice(0, lastDotIndex) : fullPath;

    return { publicId, resourceType };
  } catch {
    return null;
  }
}

export async function uploadMediaAction(formData: FormData): Promise<void> {
  await requireAdminSession();

  if (!formData || typeof formData.get !== "function") return;

  const file = formData.get("file");
  if (!file || typeof file === "string" || typeof file.arrayBuffer !== "function" || file.size === 0) return;

  if (file.size > MAX_UPLOAD_BYTES) {
    rejectUpload("too_large");
  }

  const buffer = Buffer.from(await file.arrayBuffer());
  const bytes = new Uint8Array(buffer);

  const detected = detectType(bytes);
  if (!detected) {
    rejectUpload("unsupported_type");
  }

  const declaredMime = (file.type || "").toLowerCase();
  const isGenericMime = declaredMime === "" || declaredMime === "application/octet-stream";
  if (!isGenericMime && !detected.declaredMimes.includes(declaredMime)) {
    rejectUpload("type_mismatch");
  }

  let finalUrl: string;
  let storedFilename: string;

  if (isCloudinaryConfigured()) {
    try {
      const resourceType = detected.mime.startsWith("video") ? "video" : "image";
      const uploadResult = await uploadToCloudinary(buffer, "hujurat-solar", resourceType);
      finalUrl = uploadResult.secure_url;
      storedFilename = path.basename(file.name).slice(0, 255) || `${uploadResult.public_id}${detected.extension}`;
    } catch (err) {
      console.error("Cloudinary upload error:", err);
      rejectUpload("upload_failed");
    }
  } else {
    if (process.env.VERCEL) {
      console.error(
        "[media] File uploads on Vercel require Cloudinary configuration because the serverless filesystem is read-only. Please set CLOUDINARY_URL or CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, and CLOUDINARY_API_SECRET in your Vercel Project Settings -> Environment Variables.",
      );
      rejectUpload("upload_failed");
    }

    await mkdir(UPLOAD_DIR, { recursive: true });
    // The client never chooses the on-disk name.
    const filename = `${Date.now()}-${crypto.randomUUID()}${detected.extension}`;
    await writeFile(path.join(UPLOAD_DIR, filename), bytes);
    finalUrl = `/uploads/${filename}`;
    storedFilename = path.basename(file.name).slice(0, 255) || filename;
  }

  await db.insert(media).values({
    url: finalUrl,
    filename: storedFilename,
    mimeType: detected.mime,
    size: file.size,
    alt: String(formData.get("alt") || "").slice(0, 255),
    caption: String(formData.get("caption") || "").slice(0, 255),
  });

  revalidatePath("/dashboard/media");
}

export async function deleteMediaAction(id: number) {
  await requireAdminSession();

  const mediaId = toPositiveInt(id);
  if (!mediaId) return;

  const rows = await db.select().from(media).where(eq(media.id, mediaId)).limit(1);
  const item = rows[0];

  if (item) {
    if (item.url.startsWith("/uploads/")) {
      // Local file cleanup
      const uploadRoot = path.resolve(UPLOAD_DIR);
      const target = path.resolve(uploadRoot, path.basename(item.url));

      if (target.startsWith(uploadRoot + path.sep)) {
        try {
          await unlink(target);
        } catch {
          // ignore missing file
        }
      }
    } else if (item.url.includes("cloudinary.com") && isCloudinaryConfigured()) {
      // Cloudinary asset cleanup
      const extracted = extractCloudinaryPublicId(item.url);
      if (extracted) {
        try {
          const cloudinary = getCloudinaryClient();
          await cloudinary.uploader.destroy(extracted.publicId, {
            resource_type: extracted.resourceType,
          });
        } catch (err) {
          console.error("Failed to delete Cloudinary asset:", err);
        }
      }
    }
  }

  await db.delete(media).where(eq(media.id, mediaId));
  revalidatePath("/dashboard/media");
}

